### ISSUE TITLE
Unable to change channel names/labels (biosemi plugin)

### ISSUE THREAD

**Issue by DouweHorsthuis** [labstreaminglayer/App-BioSemi#6]
Good afternoon,
I've been trying a lot of different ways to get the Matlab to change the channels A1-B32 to Fp1,Fp2 Etc. But non of the changes seem to actually make a difference when I am seeing the data in matlab. 
When I use Bio-Semi's Actiview, I can change the channels by using a different configuration file.

**Comment by dmedine** [comment]
This app has not been under active development for several years. There is no way to change the channel labels in the app. The labels reflect directly what is reported by the hardware device, which is the A1-B32 etc. Activeview allows for these channel labels to be remapped to (e.g.) 10-20 labels. I'm not sure what you are doing in Matlab, but maybe you could remap the labels there. Otherwise, someone will have to come along and implement channel labeling in this app's code.

**Comment by dmedine** [comment]
Actually, what would be much better is if BioSemi were to implement an LSL output in Activeview. That would eliminate a lot of problems (including the fact that GSR is currently output as raw data by the app). However, that would necessitate an LSL library wrapper for LabView which is something that I don't think anyone has any desire to create.

**Comment by DouweHorsthuis** [comment]
We use the vis_stream function in matlab to display the raw data as we collect it. At the same time we are collecting data from the optitrack system, that we don't display. But it's unfortunate that there is no easy way to change the numbers. 

Indeed, in Actieview it's easy to change names. But when I look more into the vis_stream function I don't see an somewhat easy solution to the issue. We'll just keep using a paper converter so we can take notes of bad channels. Also I couldn't agree more that the implementation you talk about would be wonderful. I think that the visual representation of the raw data in a different software is always something to get used to, and might cause a slight drop in quality control. But I guess these are all problems that we can deal with on the floor instead of in the software. Just a case of more practice I guess

Anyway thanks for your time.
